# fly.toml app configuration file generated for thimble-backend on 2026-05-29T21:16:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thimble-backend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[http_service.sticky_sessions]
  enabled = true

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
